language: python

python:
- "2.7"
- "3.5"

install: pip install tox-travis

script: tox

# 
# env:
# - TOXENV=py27-d16
# - TOXENV=py27-d17
# - TOXENV=py34-d17
# - TOXENV=cov
# 
branches:
  only:
    - master
#     - develop

# after_script:
# - if [ $TOXENV == "cov" ]; then
#     pip install --quiet --use-mirrors coveralls;
#     coveralls;
#   fi